title: adrian.lafond
author: Adrian Lafond
email: "&#109;&#097;&#105;&#108;&#064;&#097;&#100;&#114;&#105;&#097;&#110;&#108;&#097;&#102;&#111;&#110;&#100;&#046;&#099;&#111;&#109;"
url: "https://adrianlafond.com"

sass:
  sass_dir: _sass

exclude: [node_modules,webpack,_javascript]
